#!/bin/bash

start() {
	bash /var/www/html/testsadena/www/shell/automatchtest.sh &
	bash /var/www/html/testsadena/www/shell/autoproctest.sh &
	bash /var/www/html/testsadena/www/shell/autopushtest.sh &
	
	echo "Daemon started."
}
 
stop() {
	pkill -f "/testsadena/www/shell/automatchtest.sh"
	pkill -f "/testsadena/www/shell/autoproctest.sh"
	pkill -f "/testsadena/www/shell/autopushtest.sh"
 
	echo -e "\nDaemon stopped."
	return 1
}
 
restart() {
	stop	
	sleep 2 
	start
	return $?
}
 
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
  	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 2
esac
 
exit $?
